### PR TITLE
Create config-cn.js

### PR DESCRIPTION
**Pull request by holton-jiang**

### CODE REVIEW

**Comment by jacksonh** [comment]
Hey, sorry for the delay in reviewing these, i think because it is a new repo i missed the notifications.

**Comment by jacksonh** [comment]
For this one, I have upgraded our Vitepress installation and create a new config file to integrate all the new translation files, and I copied these translations in and commented out the missing items. I will create a new pull request and update.

**Comment by holton-jiang** [comment]
> 

Okay, thanks for your hard work.

**Comment by holton-jiang** [comment]
> For this one, I have upgraded our Vitepress installation and create a new config file to integrate all the new translation files, and I copied these translations in and commented out the missing items. I will create a new pull request and update.

I'll translate the rest when I have time.

**Pull request closed without merging**
