### PR TITLE
Create privacy-policy.md

### PR DESCRIPTION
**Pull request by holton-jiang**

### CODE REVIEW

**Comment by jacksonh** [comment]
Thank you. I think I am going to work on the english version of this one a little bit, I might ask for your help when done.

**Comment by holton-jiang** [comment]
> Thank you. I think I am going to work on the english version of this one a little bit, I might ask for your help when done.

Ok, no problem.

**Comment by jacksonh** [comment]
Hey I will close this one for now, i think probably best to keep it only in english just so there isn't anything different in translation.

**Comment by holton-jiang** [comment]
> Hey I will close this one for now, i think probably best to keep it only in english just so there isn't anything different in translation.

Okay, I can understand.

**Pull request closed without merging**
